print("Enter marks 0f 6 subjects: ")
a = int(input(""))
b = int(input(""))
c = int(input(""))
d = int(input(""))
e = int(input(""))
f = int(input(""))
list = []
list.append(a)
list.append(b)
list.append(c)
list.append(d)
list.append(e)
list.append(f)
list.sort()
print(list)