print("Enter names of 7 fruits: ")
a = input("")
b = input("")
c = input("")
d = input("")
e = input("")
f = input("")
g = input("")
g = input("")
list = []
list.append(a)
list.append(b)
list.append(c)
list.append(d)
list.append(e)
list.append(f)
list.append(g)
print(list)